/* Bible Bubble — starter board: the line from Adam to Jesus.
 *
 * Years are AM ("anno mundi"): Genesis 5 and 11 give the pre-Abraham figures
 * exactly, so those are firm. Everything after Abraham is dated on the
 * traditional anchor of AM 0 = 4004 BC and marked approximate; the kings of
 * Judah are dated from their own "X years old when he began to reign, and he
 * reigned Y years" notices. Every figure here is editable in the app.
 */
(function (BB) {
  'use strict';

  const bc = (y) => 4004 - y;   // BC year -> AM

  /* n=name, g=sex, b=birth(AM), a=age at death, d=death(AM),
     r=role, e=era, refs, hl=highlights, kids, sp=spouses,
     par=parent already on the board, x=approximate */
  const PEOPLE = [
    /* ---------------- before the Flood ---------------- */
    { id:'adam', n:'Adam', g:'m', b:0, a:930, r:'The first man', e:'Before the Flood',
      refs:['Gen 1:26–5:5','1 Cor 15:45','Rom 5:12'],
      hl:['Formed from the dust of the ground, and God breathed into him the breath of life.',
          'Named every living creature; given the garden to work and to keep.',
          'Ate what God forbade — sin and death entered the world through him.',
          'Called the first Adam, set against Christ, "the last Adam".'],
      kids:['cain','abel','seth'], sp:['eve'] },
    { id:'eve', n:'Eve', g:'f', r:'Mother of all living', e:'Before the Flood',
      refs:['Gen 2:18–4:2','1 Tim 2:13'],
      hl:['Made from Adam’s side as a helper fit for him.',
          'Deceived by the serpent, and ate first.',
          'Heard the first promise of a rescuer: her offspring would crush the serpent’s head (Gen 3:15).'],
      kids:['cain','abel','seth'] },
    { id:'cain', n:'Cain', g:'m', r:'Worker of the ground', e:'Before the Flood',
      refs:['Gen 4:1–17','Heb 11:4','1 Jn 3:12'],
      hl:['Firstborn of Adam and Eve; brought an offering of the ground that God did not accept.',
          'Murdered his brother Abel in the field — the first death by human hands.',
          'Marked for protection and sent east of Eden to Nod, where he built a city.'] },
    { id:'abel', n:'Abel', g:'m', r:'Keeper of sheep', e:'Before the Flood',
      refs:['Gen 4:2–10','Heb 11:4','Matt 23:35'],
      hl:['Brought the firstborn of his flock, and the LORD had regard for his offering.',
          'Killed by his brother; "through his faith, though he died, he still speaks".'] },
    { id:'seth', n:'Seth', g:'m', b:130, a:912, r:'Appointed in Abel’s place', e:'Before the Flood',
      refs:['Gen 4:25–5:8','Luke 3:38'],
      hl:['Born when Adam was 130 — "God has appointed for me another offspring instead of Abel".',
          'In his days people began to call upon the name of the LORD.',
          'The line of promise runs through him, not through Cain.'],
      kids:['enosh'] },
    { id:'enosh', n:'Enosh', g:'m', b:235, a:905, e:'Before the Flood', refs:['Gen 5:9–11'],
      hl:['Fathered Kenan at 90.'], kids:['kenan'] },
    { id:'kenan', n:'Kenan', g:'m', b:325, a:910, e:'Before the Flood', refs:['Gen 5:12–14'], kids:['mahalalel'] },
    { id:'mahalalel', n:'Mahalalel', g:'m', b:395, a:895, e:'Before the Flood', refs:['Gen 5:15–17'], kids:['jared'] },
    { id:'jared', n:'Jared', g:'m', b:460, a:962, e:'Before the Flood', refs:['Gen 5:18–20'],
      hl:['Second-longest life recorded, after Methuselah.'], kids:['enoch'] },
    { id:'enoch', n:'Enoch', g:'m', b:622, a:365, r:'Walked with God', e:'Before the Flood',
      refs:['Gen 5:21–24','Heb 11:5','Jude 14–15'],
      hl:['"Enoch walked with God, and he was not, for God took him" — he did not see death.',
          'Walked with God 300 years after Methuselah was born.',
          'Prophesied that the Lord would come with ten thousands of his holy ones.'],
      kids:['methuselah'] },
    { id:'methuselah', n:'Methuselah', g:'m', b:687, a:969, e:'Before the Flood', refs:['Gen 5:25–27'],
      hl:['The longest life recorded in Scripture — 969 years.',
          'Died in AM 1656, the very year the Flood came.'], kids:['lamech'] },
    { id:'lamech', n:'Lamech', g:'m', b:874, a:777, e:'Before the Flood', refs:['Gen 5:28–31'],
      hl:['Named his son Noah: "Out of the ground that the LORD has cursed, this one shall bring us relief."',
          'Died five years before the Flood.'], kids:['noah'] },
    { id:'noah', n:'Noah', g:'m', b:1056, a:950, r:'Builder of the ark', e:'Before the Flood',
      refs:['Gen 5:32–9:29','Heb 11:7','2 Pet 2:5'],
      hl:['Righteous and blameless in his generation; he walked with God.',
          'Built the ark and entered it in his 600th year — the Flood came in AM 1656.',
          'A herald of righteousness while the ark was being built.',
          'God’s covenant with him: never again a flood, and the rainbow as its sign.',
          'Planted a vineyard afterwards, and was shamed in his tent.'],
      kids:['shem','ham','japheth'] },

    /* ---------------- after the Flood ---------------- */
    { id:'shem', n:'Shem', g:'m', b:1558, a:600, r:'Father of the Semites', e:'After the Flood',
      refs:['Gen 9:26–27','Gen 11:10–11'],
      hl:['Blessed by Noah: "Blessed be the LORD, the God of Shem."',
          'Fathered Arphaxad two years after the Flood.',
          'Outlived nine generations of his own descendants.'],
      kids:['arphaxad'] },
    { id:'ham', n:'Ham', g:'m', e:'After the Flood', r:'Father of Canaan, Cush, Mizraim and Put',
      refs:['Gen 9:20–27','Gen 10:6–20'],
      hl:['Saw his father’s nakedness and told his brothers outside.',
          'His son Canaan was cursed to be a servant to his brothers.'] },
    { id:'japheth', n:'Japheth', g:'m', e:'After the Flood', r:'Father of the coastland peoples',
      refs:['Gen 9:27','Gen 10:2–5'],
      hl:['"May God enlarge Japheth, and let him dwell in the tents of Shem."'] },
    { id:'arphaxad', n:'Arphaxad', g:'m', b:1658, a:438, e:'After the Flood', refs:['Gen 11:10–13'],
      hl:['Born two years after the Flood.'], kids:['shelah'] },
    { id:'shelah', n:'Shelah', g:'m', b:1693, a:433, e:'After the Flood', refs:['Gen 11:14–15'], kids:['eber'] },
    { id:'eber', n:'Eber', g:'m', b:1723, a:464, e:'After the Flood', refs:['Gen 11:16–17'],
      hl:['The name "Hebrew" is traced to him.',
          'Outlived Abraham — he was still alive four years after Abraham died.'], kids:['peleg'] },
    { id:'peleg', n:'Peleg', g:'m', b:1757, a:239, e:'After the Flood', refs:['Gen 10:25','Gen 11:18–19'],
      hl:['"For in his days the earth was divided" — the scattering from Babel.',
          'Lifespans halve in his generation: 464 years before him, 239 in his own.'], kids:['reu'] },
    { id:'reu', n:'Reu', g:'m', b:1787, a:239, e:'After the Flood', refs:['Gen 11:20–21'], kids:['serug'] },
    { id:'serug', n:'Serug', g:'m', b:1819, a:230, e:'After the Flood', refs:['Gen 11:22–23'], kids:['nahor'] },
    { id:'nahor', n:'Nahor', g:'m', b:1849, a:148, e:'After the Flood', refs:['Gen 11:24–25'],
      hl:['The shortest life in the line — he died before his own father Serug.'], kids:['terah'] },
    { id:'terah', n:'Terah', g:'m', b:1878, a:205, e:'After the Flood', refs:['Gen 11:26–32','Josh 24:2'],
      hl:['Set out from Ur of the Chaldeans for Canaan, but settled in Haran and stayed.',
          'Served other gods beyond the River.'], kids:['abraham'] },
    { id:'haran', n:'Haran', g:'m', r:'Son of Terah', e:'After the Flood', par:'terah',
      refs:['Gen 11:26–31'],
      hl:['Died in Ur of the Chaldeans, in his father’s lifetime and in the land of his birth.',
          'Father of Lot, who went on to Canaan with Abraham.'],
      kids:['lot'] },

    /* ---------------- the patriarchs ---------------- */
    { id:'lot', n:'Lot', g:'m', r:'Abraham’s nephew', e:'The patriarchs', par:'haran',
      refs:['Gen 12:5','Gen 13','Gen 14:12–16','Gen 19','2 Pet 2:7–8'],
      hl:['Went with Abraham into Canaan, and chose the whole Jordan valley for himself.',
          'Carried off when the four kings sacked Sodom, and brought back by his uncle.',
          'Pulled out of the city by the hand as it burned; his wife looked back.',
          'Called "righteous Lot, greatly distressed by the sensual conduct of the wicked".'] },
    { id:'abraham', n:'Abraham', g:'m', aka:['Abram'], b:2008, a:175, r:'Father of the faithful', e:'The patriarchs',
      refs:['Gen 12–25','Rom 4','Heb 11:8–19','Jas 2:23'],
      hl:['Called out of Ur: "Go from your country… and I will make of you a great nation."',
          'Believed the LORD, and it was counted to him as righteousness (Gen 15:6).',
          'Circumcision given as the sign of the covenant; renamed Abraham at 99.',
          'Offered Isaac on Mount Moriah — and God provided the ram instead.',
          'Called a friend of God; buried by Isaac and Ishmael together.'],
      kids:['ishmael','isaac'], sp:['sarah','hagar'] },
    { id:'sarah', n:'Sarah', g:'f', aka:['Sarai'], b:2018, a:127, r:'Mother of the promise', e:'The patriarchs',
      refs:['Gen 17:15–21','Gen 21','Gen 23:1','Heb 11:11'],
      hl:['Barren until 90, when she bore Isaac — "God has made laughter for me."',
          'Laughed behind the tent door at the promise, and was gently caught out.',
          'The only woman whose age at death Scripture records.'],
      kids:['isaac'] },
    { id:'hagar', n:'Hagar', g:'f', r:'Egyptian servant of Sarah', e:'The patriarchs',
      refs:['Gen 16','Gen 21:8–21','Gal 4:24–25'],
      hl:['Given to Abraham by Sarah, and fled into the wilderness when despised.',
          'Met by the angel of the LORD at a spring: she called him "You are a God of seeing".',
          'Sent away with Ishmael, and shown a well when the water ran out.'],
      kids:['ishmael'] },
    { id:'ishmael', n:'Ishmael', g:'m', b:2094, a:137, r:'Father of twelve princes', e:'The patriarchs',
      refs:['Gen 16:11–16','Gen 17:20','Gen 25:12–18'],
      hl:['Born to Abraham at 86 by Hagar — "God hears".',
          'Blessed for Abraham’s sake with twelve princes and a great nation.',
          'A wild donkey of a man, dwelling over against all his kinsmen.'] },
    { id:'isaac', n:'Isaac', g:'m', b:2108, a:180, r:'The son of promise', e:'The patriarchs',
      refs:['Gen 21–28','Gen 35:28–29','Heb 11:20'],
      hl:['Born when Abraham was 100 and Sarah 90 — his name means "he laughs".',
          'Carried the wood, was bound on the altar at Moriah, and was given back.',
          'Sowed in Gerar during famine and reaped a hundredfold that year.',
          'Blessed Jacob while meaning to bless Esau, and would not take it back.'],
      kids:['esau','jacob'], sp:['rebekah'] },
    { id:'rebekah', n:'Rebekah', g:'f', e:'The patriarchs',
      refs:['Gen 24','Gen 25:21–28','Gen 27'],
      hl:['Found at the well, and watered ten camels for a stranger.',
          'Barren twenty years; then the oracle — "the older shall serve the younger".',
          'Schemed with Jacob to secure the blessing, and never saw him again.'],
      kids:['esau','jacob'] },
    { id:'esau', n:'Esau', g:'m', aka:['Edom'], b:2168, r:'Father of the Edomites', e:'The patriarchs',
      refs:['Gen 25:24–34','Gen 27','Gen 33','Heb 12:16'],
      hl:['Born first, red and hairy, holding nothing; a skilful hunter.',
          'Sold his birthright for a bowl of red stew.',
          'Wept for the blessing he had already despised.',
          'Ran to meet Jacob after twenty years, embraced him, and wept.'] },
    { id:'jacob', n:'Jacob', g:'m', aka:['Israel'], b:2168, a:147, r:'Father of the twelve tribes', e:'The patriarchs',
      refs:['Gen 25–50','Heb 11:21'],
      hl:['Born gripping his brother’s heel — his name means "he grasps".',
          'Saw the ladder at Bethel, and God renewed the promise to him there.',
          'Served Laban twenty years for Leah and Rachel and his flocks.',
          'Wrestled until daybreak at Peniel, was crippled, and renamed Israel.',
          'Went down to Egypt at 130 and blessed Pharaoh; buried in Machpelah.'],
      kids:['reuben','simeon','levi','judah','dan','naphtali','gad','asher','issachar','zebulun','joseph','benjamin','dinah'],
      sp:['leah','rachel','bilhah','zilpah'] },
    { id:'leah', n:'Leah', g:'f', e:'The patriarchs', refs:['Gen 29:16–35','Gen 49:31'],
      hl:['The unloved wife — "when the LORD saw that Leah was hated, he opened her womb".',
          'Mother of six sons, among them Levi the priest and Judah the king.',
          'Buried with Jacob in the cave of Machpelah, not Rachel.'],
      kids:['reuben','simeon','levi','judah','issachar','zebulun','dinah'] },
    { id:'rachel', n:'Rachel', g:'f', e:'The patriarchs', refs:['Gen 29:9–30','Gen 35:16–20'],
      hl:['Jacob served fourteen years for her, and they seemed to him but a few days.',
          'Barren long, then mother of Joseph and Benjamin.',
          'Died in childbirth on the way to Bethlehem, and was buried there.'],
      kids:['joseph','benjamin'] },
    { id:'bilhah', n:'Bilhah', g:'f', r:'Rachel’s servant', e:'The patriarchs', refs:['Gen 30:1–8'],
      kids:['dan','naphtali'] },
    { id:'zilpah', n:'Zilpah', g:'f', r:'Leah’s servant', e:'The patriarchs', refs:['Gen 30:9–13'],
      kids:['gad','asher'] },

    /* ---------------- the twelve ---------------- */
    { id:'reuben', n:'Reuben', g:'m', r:'Firstborn of Jacob', e:'The twelve tribes', refs:['Gen 29:32','Gen 37:21–22','Gen 49:3–4'],
      hl:['"Unstable as water, you shall not have pre-eminence" — the birthright passed him by.',
          'Pleaded with his brothers not to kill Joseph.'] },
    { id:'simeon', n:'Simeon', g:'m', e:'The twelve tribes', refs:['Gen 34','Gen 42:24','Gen 49:5–7'],
      hl:['With Levi, took revenge on Shechem for Dinah.','Held hostage in Egypt while the brothers went home.'] },
    { id:'levi', n:'Levi', g:'m', a:137, r:'Father of the priestly tribe', e:'The twelve tribes',
      refs:['Gen 34','Gen 49:5–7','Ex 6:16'],
      hl:['Scattered in Israel for his violence — and then given the priesthood.',
          'His line carries Moses, Aaron and every priest after them.'],
      kids:['kohath'] },
    { id:'judah', n:'Judah', g:'m', r:'The royal line', e:'The twelve tribes',
      refs:['Gen 38','Gen 44:18–34','Gen 49:8–12','Rev 5:5'],
      hl:['Proposed selling Joseph rather than killing him.',
          'Offered himself as a substitute so Benjamin could go free.',
          '"The sceptre shall not depart from Judah" — kings and Messiah come from him.',
          'Father of Perez by Tamar, his daughter-in-law.'],
      kids:['perez','zerah'], sp:['tamar'] },
    { id:'dan', n:'Dan', g:'m', e:'The twelve tribes', refs:['Gen 30:6','Gen 49:16–17'] },
    { id:'naphtali', n:'Naphtali', g:'m', e:'The twelve tribes', refs:['Gen 30:8','Gen 49:21'] },
    { id:'gad', n:'Gad', g:'m', e:'The twelve tribes', refs:['Gen 30:11','Gen 49:19'] },
    { id:'asher', n:'Asher', g:'m', e:'The twelve tribes', refs:['Gen 30:13','Gen 49:20'] },
    { id:'issachar', n:'Issachar', g:'m', e:'The twelve tribes', refs:['Gen 30:18','Gen 49:14–15'] },
    { id:'zebulun', n:'Zebulun', g:'m', e:'The twelve tribes', refs:['Gen 30:20','Gen 49:13'] },
    { id:'dinah', n:'Dinah', g:'f', e:'The twelve tribes', refs:['Gen 34'],
      hl:['Her violation at Shechem brought Simeon and Levi’s revenge on the city.'] },
    { id:'joseph', n:'Joseph', g:'m', b:2259, a:110, r:'Ruler in Egypt', e:'The twelve tribes',
      refs:['Gen 37–50','Heb 11:22'],
      hl:['The coat, the dreams, and the brothers who sold him for twenty pieces of silver.',
          'Refused Potiphar’s wife and was jailed for it.',
          'Interpreted Pharaoh’s dreams and was set over all Egypt at thirty.',
          '"You meant evil against me, but God meant it for good."',
          'Made Israel swear to carry his bones out of Egypt.'] },
    { id:'benjamin', n:'Benjamin', g:'m', e:'The twelve tribes', refs:['Gen 35:18','Gen 49:27'],
      hl:['Rachel named him Ben-oni, "son of my sorrow"; his father called him Benjamin.',
          'The tribe of Saul, Israel’s first king, and of Paul.'] },
    { id:'tamar', n:'Tamar', g:'f', e:'The twelve tribes', refs:['Gen 38','Matt 1:3'],
      hl:['Widowed twice and denied Judah’s third son.',
          'Took by disguise what was owed her, and bore Perez and Zerah.',
          'The first of four women named in Matthew’s genealogy.'],
      kids:['perez','zerah'] },

    /* ---------------- Levi’s branch: the Exodus ---------------- */
    { id:'kohath', n:'Kohath', g:'m', a:133, e:'Egypt and the Exodus', refs:['Ex 6:18'], kids:['amram'] },
    { id:'amram', n:'Amram', g:'m', a:137, e:'Egypt and the Exodus', refs:['Ex 6:20'],
      kids:['aaron','moses','miriam'], sp:['jochebed'] },
    { id:'jochebed', n:'Jochebed', g:'f', e:'Egypt and the Exodus', refs:['Ex 2:1–10','Ex 6:20','Heb 11:23'],
      hl:['Hid her son three months, then set him in the reeds of the Nile.',
          'Was paid by Pharaoh’s daughter to nurse her own child.'],
      kids:['aaron','moses','miriam'] },
    { id:'moses', n:'Moses', g:'m', a:120, r:'Prophet and lawgiver', e:'Egypt and the Exodus',
      refs:['Ex 2–Deut 34','Heb 11:24–29'],
      hl:['Drawn out of the Nile and raised in Pharaoh’s house.',
          'Fled to Midian at 40; met God in the burning bush at 80.',
          'Led Israel out of Egypt, through the sea, and received the Law at Sinai.',
          'Spoke with God face to face, as a man speaks to his friend.',
          'Saw the land from Nebo but did not enter; died at 120, his eye undimmed.'] },
    { id:'aaron', n:'Aaron', g:'m', a:123, r:'First high priest', e:'Egypt and the Exodus',
      refs:['Ex 4:14–16','Ex 32','Num 17','Num 20:22–29'],
      hl:['Spoke for Moses before Pharaoh.',
          'Made the golden calf while Moses was on the mountain.',
          'His rod budded overnight, confirming his line as priests.',
          'Died on Mount Hor; the priesthood passed to Eleazar.'] },
    { id:'miriam', n:'Miriam', g:'f', r:'Prophetess', e:'Egypt and the Exodus',
      refs:['Ex 2:4–8','Ex 15:20–21','Num 12'],
      hl:['Watched the basket in the reeds and fetched the baby’s own mother.',
          'Led the women with tambourines after the sea: "Sing to the LORD…"',
          'Struck with leprosy for speaking against Moses, and healed after seven days.'] },

    /* ---------------- Judah to David ---------------- */
    { id:'zerah', n:'Zerah', g:'m', e:'Judah’s line', refs:['Gen 38:30'],
      hl:['The twin whose hand came out first, with the scarlet thread.'] },
    { id:'perez', n:'Perez', g:'m', e:'Judah’s line', refs:['Gen 38:29','Ruth 4:18','Matt 1:3'],
      hl:['"What a breach you have made for yourself!" — born ahead of his twin.'], kids:['hezron'] },
    { id:'hezron', n:'Hezron', g:'m', e:'Judah’s line', refs:['Ruth 4:18','Matt 1:3'], kids:['ram'] },
    { id:'ram', n:'Ram', g:'m', e:'Judah’s line', refs:['Ruth 4:19','Matt 1:3–4'], kids:['amminadab'] },
    { id:'amminadab', n:'Amminadab', g:'m', e:'Judah’s line', refs:['Ruth 4:19','Num 1:7'], kids:['nahshon'] },
    { id:'nahshon', n:'Nahshon', g:'m', r:'Chief of Judah in the wilderness', e:'Judah’s line',
      refs:['Num 1:7','Num 7:12','Ruth 4:20'],
      hl:['Led the tribe of Judah out of Sinai, first of all the tribes to march.'], kids:['salmon'] },
    { id:'salmon', n:'Salmon', g:'m', e:'Judah’s line', refs:['Ruth 4:21','Matt 1:5'], kids:['boaz'], sp:['rahab'] },
    { id:'rahab', n:'Rahab', g:'f', r:'Of Jericho', e:'Judah’s line',
      refs:['Josh 2','Josh 6:22–25','Heb 11:31','Jas 2:25'],
      hl:['Hid the spies on her roof and sent the search party the wrong way.',
          '"The LORD your God, he is God in the heavens above and on the earth beneath."',
          'Hung the scarlet cord from her window and her whole household was spared.',
          'Named among the faithful, and in the genealogy of the Messiah.'],
      kids:['boaz'] },
    { id:'boaz', n:'Boaz', g:'m', r:'Kinsman-redeemer', e:'Judah’s line', refs:['Ruth 2–4','Matt 1:5'],
      hl:['A worthy man of Bethlehem who told his reapers to leave grain for Ruth on purpose.',
          'Redeemed the field and the widow with it, before the elders at the gate.'],
      kids:['obed'], sp:['ruth'] },
    { id:'ruth', n:'Ruth', g:'f', r:'The Moabitess', e:'Judah’s line', refs:['Ruth 1–4','Matt 1:5'],
      hl:['"Where you go I will go… your people shall be my people, and your God my God."',
          'Gleaned in the field of Boaz and happened upon her redeemer.',
          'A foreigner who became the great-grandmother of David.'],
      kids:['obed'] },
    { id:'obed', n:'Obed', g:'m', e:'Judah’s line', refs:['Ruth 4:17','Matt 1:5'],
      hl:['Laid in Naomi’s lap — "a son has been born to Naomi".'], kids:['jesse'] },
    { id:'jesse', n:'Jesse', g:'m', r:'The Bethlehemite', e:'Judah’s line', refs:['1 Sam 16','Isa 11:1'],
      hl:['Paraded seven sons before Samuel before anyone thought to send for the youngest.',
          '"There shall come forth a shoot from the stump of Jesse."'],
      kids:['david'] },

    /* ---------------- the kings ---------------- */
    { id:'david', n:'David', g:'m', b:bc(1040), a:70, x:1, r:'King of Israel', e:'The united kingdom',
      refs:['1 Sam 16 – 1 Kgs 2','2 Sam 7','Ps 51','Acts 13:22'],
      hl:['A shepherd boy anointed by Samuel while his brothers watched.',
          'Killed Goliath with a sling and a stone, in the name of the LORD of hosts.',
          'Reigned forty years — seven in Hebron, thirty-three in Jerusalem.',
          'Took Bathsheba, lost the child, and wrote "Create in me a clean heart".',
          'Promised a throne established for ever — the covenant the Gospels pick up.'],
      kids:['solomon','nathan_s','absalom','amnon'], sp:['bathsheba'] },
    { id:'bathsheba', n:'Bathsheba', g:'f', e:'The united kingdom', refs:['2 Sam 11–12','1 Kgs 1','Matt 1:6'],
      hl:['Wife of Uriah the Hittite, who was killed to hide what had been done.',
          'Mother of Solomon; she secured his throne when Adonijah moved first.'],
      kids:['solomon'] },
    { id:'amnon', n:'Amnon', g:'m', e:'The united kingdom', refs:['2 Sam 13'],
      hl:['David’s firstborn; violated his sister Tamar and was killed by Absalom.'] },
    { id:'absalom', n:'Absalom', g:'m', e:'The united kingdom', refs:['2 Sam 14–18'],
      hl:['Stole the hearts of Israel at the gate and took the kingdom by revolt.',
          'Caught by his head in an oak and killed against David’s orders.',
          '"O Absalom, my son, my son!"'] },
    { id:'tamar_d', n:'Tamar', g:'f', r:'Daughter of David', e:'The united kingdom', par:'david',
      refs:['2 Sam 13'],
      hl:['Absalom’s sister, in the long robe with sleeves the king’s daughters wore.',
          'Wronged by her half-brother Amnon and put out of doors.',
          'Lived on, desolate, in her brother Absalom’s house.'] },
    { id:'nathan_s', n:'Nathan', g:'m', r:'Son of David', e:'The united kingdom', refs:['2 Sam 5:14','Luke 3:31','Zech 12:12'],
      hl:['Luke’s genealogy runs to Jesus through this son of David, not through Solomon.'] },
    { id:'solomon', n:'Solomon', g:'m', b:bc(990), d:bc(931), x:1, r:'King, builder of the temple', e:'The united kingdom',
      refs:['1 Kgs 1–11','Prov','Eccl'],
      hl:['Asked for an understanding mind to govern, and was given wisdom and much else.',
          'Built the temple in seven years, and his own house in thirteen.',
          'Wisest of men, who wrote proverbs and songs by the thousand.',
          'His many wives turned his heart, and the kingdom was torn in two after him.'],
      kids:['rehoboam'] },
    { id:'rehoboam', n:'Rehoboam', g:'m', b:bc(972), a:58, x:1, r:'King of Judah', e:'Kings of Judah',
      refs:['1 Kgs 12','1 Kgs 14:21–31','2 Chr 10–12'],
      hl:['Took the young men’s advice: "My father disciplined you with whips…"',
          'Ten tribes tore away; only Judah and Benjamin stayed.'], kids:['abijah'] },
    { id:'abijah', n:'Abijah', g:'m', aka:['Abijam'], d:bc(911), x:1, r:'King of Judah', e:'Kings of Judah',
      refs:['1 Kgs 15:1–8','2 Chr 13'],
      hl:['Reigned three years; won a great battle against Jeroboam by calling on the LORD.'], kids:['asa'] },
    { id:'asa', n:'Asa', g:'m', d:bc(870), x:1, r:'King of Judah', e:'Kings of Judah',
      refs:['1 Kgs 15:9–24','2 Chr 14–16'],
      hl:['Reigned 41 years and did what was right; tore down the idols and even deposed his grandmother.',
          'In his old age he leaned on physicians and on Syria rather than the LORD.'], kids:['jehoshaphat'] },
    { id:'jehoshaphat', n:'Jehoshaphat', g:'m', b:bc(908), a:60, x:1, r:'King of Judah', e:'Kings of Judah',
      refs:['1 Kgs 22','2 Chr 17–20'],
      hl:['Sent teachers with the book of the Law through all the cities of Judah.',
          'Faced a vast army with a choir in front of the troops.',
          'Allied himself with Ahab’s house, and it cost his son dearly.'], kids:['joram'] },
    { id:'joram', n:'Joram', g:'m', aka:['Jehoram'], b:bc(881), a:40, x:1, r:'King of Judah', e:'Kings of Judah',
      refs:['2 Kgs 8:16–24','2 Chr 21'],
      hl:['Married Athaliah of Ahab’s house and walked in their ways.',
          'Killed his own brothers to secure the throne; died unmourned.'], kids:['ahaziah_k'] },
    { id:'athaliah', n:'Athaliah', g:'f', d:bc(835), x:1, r:'Queen of Judah, of the house of Ahab', e:'Kings of Judah',
      refs:['2 Kgs 8:18','2 Kgs 11','2 Chr 22:10–23:21'],
      hl:['Brought the ways of Ahab’s house into the line of David by marrying Joram.',
          'Destroyed the royal family when her son died, and reigned six years herself.',
          'Undone when Joash was crowned in the temple; put to death at the horses’ entrance.'],
      kids:['ahaziah_k'], sp:['joram'] },
    { id:'ahaziah_k', n:'Ahaziah', g:'m', b:bc(864), a:23, x:1, r:'King of Judah', e:'Kings of Judah',
      refs:['2 Kgs 8:25–29','2 Chr 22:1–9'],
      hl:['Reigned one year; killed by Jehu alongside the house of Ahab.',
          'Matthew’s genealogy skips him, Joash and Amaziah, going straight from Joram to Uzziah.'],
      kids:['joash'] },
    { id:'joash', n:'Joash', g:'m', aka:['Jehoash'], b:bc(842), a:46, x:1, r:'King of Judah', e:'Kings of Judah',
      refs:['2 Kgs 11–12','2 Chr 22:10–24:27'],
      hl:['Hidden in the temple as a baby while Athaliah killed the rest of the royal line.',
          'Crowned at seven; repaired the temple with a chest by the altar.',
          'Turned after Jehoiada the priest died, and murdered his son Zechariah.'], kids:['amaziah'] },
    { id:'amaziah', n:'Amaziah', g:'m', b:bc(821), a:54, x:1, r:'King of Judah', e:'Kings of Judah',
      refs:['2 Kgs 14:1–20','2 Chr 25'],
      hl:['Did right, but not with a whole heart — he worshipped the gods of the people he had just defeated.'],
      kids:['uzziah'] },
    { id:'uzziah', n:'Uzziah', g:'m', aka:['Azariah'], b:bc(808), a:68, x:1, r:'King of Judah', e:'Kings of Judah',
      refs:['2 Kgs 15:1–7','2 Chr 26','Isa 6:1'],
      hl:['Crowned at sixteen; strong while he sought the LORD.',
          'Grew proud, burned incense in the temple, and was struck with leprosy to his death.',
          '"In the year that King Uzziah died I saw the Lord…" — Isaiah’s vision.'], kids:['jotham'] },
    { id:'jotham', n:'Jotham', g:'m', b:bc(775), a:43, x:1, r:'King of Judah', e:'Kings of Judah',
      refs:['2 Kgs 15:32–38','2 Chr 27'],
      hl:['"He became mighty, because he ordered his ways before the LORD his God."'], kids:['ahaz'] },
    { id:'ahaz', n:'Ahaz', g:'m', b:bc(755), a:40, x:1, r:'King of Judah', e:'Kings of Judah',
      refs:['2 Kgs 16','2 Chr 28','Isa 7'],
      hl:['Burned his own son as an offering and stripped the temple to pay Assyria.',
          'Refused a sign from God — and was given one anyway: "the virgin shall conceive".'], kids:['hezekiah'] },
    { id:'hezekiah', n:'Hezekiah', g:'m', b:bc(740), a:54, x:1, r:'King of Judah', e:'Kings of Judah',
      refs:['2 Kgs 18–20','2 Chr 29–32','Isa 36–39'],
      hl:['"He trusted in the LORD… there was none like him among all the kings of Judah."',
          'Cleansed the temple, kept a great Passover, and broke the bronze serpent in pieces.',
          'Spread Sennacherib’s letter before the LORD, and Jerusalem was spared.',
          'Given fifteen more years when he wept, and the shadow went back ten steps.'], kids:['manasseh'] },
    { id:'manasseh', n:'Manasseh', g:'m', b:bc(709), a:67, x:1, r:'King of Judah', e:'Kings of Judah',
      refs:['2 Kgs 21:1–18','2 Chr 33:1–20'],
      hl:['The longest reign in Judah — 55 years — and the worst.',
          'Taken to Babylon with hooks, and there he humbled himself and was restored.'], kids:['amon'] },
    { id:'amon', n:'Amon', g:'m', b:bc(664), a:24, x:1, r:'King of Judah', e:'Kings of Judah',
      refs:['2 Kgs 21:19–26','2 Chr 33:21–25'],
      hl:['Reigned two years and was killed by his own servants.'], kids:['josiah'] },
    { id:'josiah', n:'Josiah', g:'m', b:bc(648), a:39, x:1, r:'King of Judah', e:'Kings of Judah',
      refs:['2 Kgs 22–23','2 Chr 34–35'],
      hl:['Crowned at eight; began to seek God at sixteen.',
          'The book of the Law was found in the temple, and he tore his clothes when he heard it.',
          'Kept a Passover unlike any since the days of the judges.',
          'Killed at Megiddo; Jeremiah made a lament for him.'], kids:['jehoiakim'] },
    { id:'jehoiakim', n:'Jehoiakim', g:'m', b:bc(634), a:36, x:1, r:'King of Judah', e:'Kings of Judah',
      refs:['2 Kgs 23:34–24:7','Jer 36'],
      hl:['Cut Jeremiah’s scroll column by column and burned it in the firepot.',
          'Matthew’s list passes from Josiah to Jeconiah, leaving him out.'], kids:['jeconiah'] },
    { id:'jeconiah', n:'Jeconiah', g:'m', aka:['Jehoiachin','Coniah'], b:bc(615), x:1, r:'King of Judah', e:'Exile and return',
      refs:['2 Kgs 24:8–17','2 Kgs 25:27–30','Jer 22:24–30','Matt 1:11–12'],
      hl:['Reigned three months and was carried to Babylon with the treasures of the temple.',
          'Cursed: "none of his offspring shall sit on the throne of David" — yet the line runs on through him.',
          'Freed from prison after 37 years and ate at the king of Babylon’s table.'],
      kids:['shealtiel'] },

    /* ---------------- exile to the Gospel ---------------- */
    { id:'shealtiel', n:'Shealtiel', g:'m', e:'Exile and return', refs:['1 Chr 3:17','Matt 1:12','Luke 3:27'], kids:['zerubbabel'] },
    { id:'zerubbabel', n:'Zerubbabel', g:'m', b:bc(570), d:bc(510), x:1, r:'Governor of Judah', e:'Exile and return',
      refs:['Ezra 3–5','Hag 2:23','Zech 4','Matt 1:12–13'],
      hl:['Led the first return from Babylon and laid the temple’s foundation.',
          '"Not by might, nor by power, but by my Spirit, says the LORD of hosts."',
          'Called God’s signet ring — the curse on Jeconiah’s line answered.'], kids:['abiud'] },
    { id:'abiud', n:'Abiud', g:'m', e:'Exile and return', refs:['Matt 1:13'], kids:['eliakim'] },
    { id:'eliakim', n:'Eliakim', g:'m', e:'Exile and return', refs:['Matt 1:13'], kids:['azor'] },
    { id:'azor', n:'Azor', g:'m', e:'Exile and return', refs:['Matt 1:13–14'], kids:['zadok'] },
    { id:'zadok', n:'Zadok', g:'m', e:'Exile and return', refs:['Matt 1:14'], kids:['achim'] },
    { id:'achim', n:'Achim', g:'m', e:'Exile and return', refs:['Matt 1:14'], kids:['eliud'] },
    { id:'eliud', n:'Eliud', g:'m', e:'Exile and return', refs:['Matt 1:14–15'], kids:['eleazar'] },
    { id:'eleazar', n:'Eleazar', g:'m', e:'Exile and return', refs:['Matt 1:15'], kids:['matthan'] },
    { id:'matthan', n:'Matthan', g:'m', e:'Exile and return', refs:['Matt 1:15'], kids:['jacob_f'] },
    { id:'jacob_f', n:'Jacob', g:'m', r:'Father of Joseph', e:'Exile and return', refs:['Matt 1:15–16'], kids:['joseph_n'] },
    { id:'joseph_n', n:'Joseph', g:'m', r:'Carpenter of Nazareth', e:'The Gospel',
      refs:['Matt 1:18–25','Matt 2:13–23','Luke 2'],
      hl:['A just man, who resolved to divorce Mary quietly rather than shame her.',
          'Took her as his wife when the angel spoke, and named the child Jesus.',
          'Took them to Egypt by night, and settled in Nazareth on the way back.'],
      kids:['jesus'], sp:['mary'] },
    { id:'mary', n:'Mary', g:'f', e:'The Gospel',
      refs:['Luke 1:26–56','Luke 2','John 19:25–27','Acts 1:14'],
      hl:['"Behold, I am the servant of the Lord; let it be to me according to your word."',
          'Her song magnifies the God who fills the hungry and sends the rich away empty.',
          'Kept all these things, pondering them in her heart.',
          'Stood by the cross, and was there with the disciples at prayer afterwards.'],
      kids:['jesus'] },
    { id:'jesus', n:'Jesus', g:'m', aka:['Christ','Immanuel'], b:bc(5), d:4033, x:1, r:'Son of David, Son of God', e:'The Gospel',
      refs:['Matt 1:1–17','Luke 3:23–38','Rom 1:3','Rev 22:16'],
      hl:['"The book of the genealogy of Jesus Christ, the son of David, the son of Abraham."',
          'Born in Bethlehem, David’s town, as the prophets had said.',
          'Matthew traces him through Solomon and the kings; Luke traces him back past Abraham to Adam.',
          'The offspring promised in Eden who crushes the serpent’s head.'] },
  ];

  /* Links that are not lineage. a=from, b=to, k=kind, l=label, note=where it is written.
     Where the kind has a direction, a is the one who acts: a mentors b, a rescued b. */
  const BONDS = [
    /* ---------------- before and after the Flood ---------------- */
    { a:'cain', b:'abel', k:'harmed', l:'Killed him in the field', note:'Gen 4:8' },
    { a:'ham', b:'noah', k:'harmed', l:'Saw his father uncovered and told his brothers outside', note:'Gen 9:22' },
    { a:'shem', b:'japheth', k:'ally', l:'Walked in backward with a garment to cover their father', note:'Gen 9:23' },

    /* ---------------- the patriarchs ---------------- */
    { a:'abraham', b:'sarah', k:'kin', l:'Half-sister as well as wife — "the daughter of my father"', note:'Gen 20:12' },
    { a:'hagar', b:'sarah', k:'servant', l:'Her Egyptian servant, handed to Abraham in her place', note:'Gen 16:1–3' },
    { a:'sarah', b:'hagar', k:'harmed', l:'Dealt harshly with her until she fled into the wilderness', note:'Gen 16:6' },
    { a:'abraham', b:'lot', k:'rescued', l:'Armed his men and brought him back from the four kings', note:'Gen 14:14–16' },
    { a:'ishmael', b:'isaac', k:'rival', l:'Mocked him at the feast on the day he was weaned', note:'Gen 21:9; Gal 4:29' },
    { a:'rebekah', b:'jacob', k:'ally', l:'Dressed him in Esau’s clothes and took the curse on herself', note:'Gen 27:5–17' },
    { a:'jacob', b:'esau', k:'rival', l:'Bought his birthright for stew, then took his blessing', note:'Gen 25:29–34; Gen 27:1–29' },
    { a:'esau', b:'jacob', k:'met', l:'Ran to meet him after twenty years and fell on his neck', note:'Gen 33:4' },
    { a:'leah', b:'rachel', k:'kin', l:'Sisters — Jacob served seven years for each of them', note:'Gen 29:16–28' },
    { a:'rachel', b:'leah', k:'rival', l:'Envied her sons, and traded a night for mandrakes', note:'Gen 30:1–16' },
    { a:'bilhah', b:'rachel', k:'servant', l:'Bore Dan and Naphtali on her mistress’s knees', note:'Gen 30:3–8' },
    { a:'zilpah', b:'leah', k:'servant', l:'Given to Jacob when her mistress stopped bearing', note:'Gen 30:9–13' },

    /* ---------------- the twelve ---------------- */
    { a:'reuben', b:'bilhah', k:'harmed', l:'Lay with his father’s concubine, and lost his birthright', note:'Gen 35:22; Gen 49:4; 1 Chr 5:1' },
    { a:'simeon', b:'levi', k:'ally', l:'Took their swords together against Shechem for Dinah', note:'Gen 34:25–26' },
    { a:'judah', b:'joseph', k:'harmed', l:'Proposed selling him to the Ishmaelites for twenty pieces', note:'Gen 37:26–28' },
    { a:'reuben', b:'joseph', k:'rescued', l:'Talked them out of killing him, meaning to take him home', note:'Gen 37:21–22' },
    { a:'joseph', b:'simeon', k:'harmed', l:'Bound him before their eyes and kept him back in Egypt', note:'Gen 42:24' },
    { a:'judah', b:'benjamin', k:'rescued', l:'Stood surety for him, and offered to stay in his place', note:'Gen 43:9; Gen 44:33' },
    { a:'jacob', b:'joseph', k:'covenant', l:'Made him swear to bury him with his fathers, not in Egypt', note:'Gen 47:29–31' },
    { a:'judah', b:'tamar', k:'harmed', l:'Withheld Shelah, then owned she was the righteous one', note:'Gen 38:11, 26' },

    /* ---------------- Egypt and the Exodus ---------------- */
    { a:'moses', b:'aaron', k:'anointed', l:'Poured the oil on his head and made him high priest', note:'Lev 8:12' },
    { a:'aaron', b:'moses', k:'ally', l:'Spoke for him before Pharaoh — "he shall be your mouth"', note:'Ex 4:14–16' },
    { a:'miriam', b:'moses', k:'rescued', l:'Watched the basket and fetched his own mother to nurse him', note:'Ex 2:4–8' },
    { a:'miriam', b:'moses', k:'rival', l:'Spoke against him with Aaron, and was leprous seven days', note:'Num 12:1–15' },

    /* ---------------- Judah’s line ---------------- */
    { a:'boaz', b:'ruth', k:'rescued', l:'Redeemed her when the nearer kinsman would not', note:'Ruth 4:1–10' },

    /* ---------------- the kings ---------------- */
    { a:'david', b:'bathsheba', k:'harmed', l:'Sent for her, then had her husband set where he would fall', note:'2 Sam 11:2–17' },
    { a:'david', b:'solomon', k:'mentor', l:'Charged him at the last: "Show yourself a man"', note:'1 Kgs 2:1–4' },
    { a:'amnon', b:'tamar_d', k:'harmed', l:'Forced his sister, then sent her out and bolted the door', note:'2 Sam 13:14–17' },
    { a:'absalom', b:'amnon', k:'harmed', l:'Had him struck down at the sheepshearing two years after', note:'2 Sam 13:23–29' },
    { a:'absalom', b:'tamar_d', k:'rescued', l:'Kept her in his house, and killed Amnon for what he did', note:'2 Sam 13:20–29' },
    { a:'absalom', b:'david', k:'rival', l:'Stole the hearts of Israel and drove him out of Jerusalem', note:'2 Sam 15:6–14' },
    { a:'rehoboam', b:'solomon', k:'other', l:'Took his father’s kingdom and lost ten tribes of it', note:'1 Kgs 12:4–19' },
    { a:'athaliah', b:'joash', k:'harmed', l:'Destroyed the royal sons; he was hidden from her as a baby', note:'2 Kgs 11:1–3' },
    { a:'hezekiah', b:'ahaz', k:'other', l:'Opened the temple doors his father had shut', note:'2 Chr 28:24; 2 Chr 29:3' },
    { a:'manasseh', b:'hezekiah', k:'other', l:'Rebuilt every high place his father had broken down', note:'2 Kgs 21:3' },
    { a:'josiah', b:'manasseh', k:'other', l:'Pulled down the altars his grandfather had built', note:'2 Kgs 23:12' },

    /* ---------------- the Gospel ---------------- */
    { a:'joseph_n', b:'jesus', k:'rescued', l:'Took him to Egypt by night, out of Herod’s reach', note:'Matt 2:13–14' },
  ];

  const ERA_COLOR = {
    'Before the Flood':   'sand',
    'After the Flood':    'teal',
    'The patriarchs':     'clay',
    'The twelve tribes':  'olive',
    'Egypt and the Exodus':'stone',
    'Judah’s line':  'sky',
    'The united kingdom': 'plum',
    'Kings of Judah':     'sky',
    'Exile and return':   'stone',
    'The Gospel':         'rose',
  };

  const ABOUT =
    'The line from Adam to Jesus, drawn from Genesis 5 and 11, Ruth 4, ' +
    '1 Chronicles, and the genealogies in Matthew 1 and Luke 3.\n\n' +
    'Years before Abraham are exact: Genesis gives each father’s age at his son’s birth ' +
    'and his age at death, so the whole chain is fixed relative to creation (AM). ' +
    'Later dates are marked "c." and rest on the traditional anchor of AM 0 = 4004 BC; ' +
    'the kings of Judah are dated from their own accession ages and reign lengths. ' +
    'Change the anchor, the dates, or anything else — this is your board.';

  /** Build a full document from the compact table above. */
  function build() {
    const M = BB.model, U = BB.util;
    const doc = M.blankDoc('Genesis → Gospel');
    doc.settings.yearMode = 'both';

    PEOPLE.forEach(row => {
      const p = M.blankPerson({
        id: row.id,
        name: row.n,
        aka: row.aka || [],
        sex: row.g || '',
        role: row.r || '',
        era: row.e || '',
        birth: row.b === undefined ? null : row.b,
        death: row.d === undefined ? null : row.d,
        age: row.a === undefined ? null : row.a,
        approx: !!row.x,
        refs: row.refs || [],
        highlights: row.hl || [],
        tags: row.e ? [row.e] : [],
        color: ERA_COLOR[row.e] || 'sand',
      });
      doc.people[p.id] = p;
    });

    const add = (from, to, type) => {
      if (!doc.people[from] || !doc.people[to] || from === to) return;
      const dup = Object.values(doc.links).some(l => l.type === type &&
        ((l.from === from && l.to === to) || (type !== 'parent' && l.from === to && l.to === from)));
      if (dup) return;
      const id = U.uid('l');
      doc.links[id] = { id, from, to, type, kind: '', label: '', note: '' };
    };
    PEOPLE.forEach(row => {
      if (row.par) add(row.par, row.id, 'parent');
      (row.kids || []).forEach(k => add(row.id, k, 'parent'));
      (row.sp || []).forEach(s => add(row.id, s, 'spouse'));
    });

    // A pair may stand in two relations, so a bond only clashes with its own kind.
    BONDS.forEach(row => {
      if (!doc.people[row.a] || !doc.people[row.b] || row.a === row.b) return;
      const dup = Object.values(doc.links).some(l => l.type === 'other' && l.kind === row.k &&
        ((l.from === row.a && l.to === row.b) || (l.from === row.b && l.to === row.a)));
      if (dup) return;
      const id = U.uid('l');
      doc.links[id] = { id, from: row.a, to: row.b, type: 'other',
        kind: row.k, label: row.l, note: row.note || '' };
    });

    doc.notes = ABOUT;
    return doc;
  }

  BB.seed = { build, ABOUT, count: PEOPLE.length, bonds: BONDS.length };
})(window.BB);
